sudo: required
services:
  - docker

before_install:
  - docker build -t marcusx/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true marcusx/react-test npm test

after_success:
  - docker build -t marcusx/multi-client ./client
  - docker build -t marcusx/multi-nginx ./nginx
  - docker build -t marcusx/multi-server ./server
  - docker build -t marcusx/multi-worker ./worker
  # Log in to the docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub.
  - docker push marcusx/multi-client
  - docker push marcusx/multi-nginx
  - docker push marcusx/multi-server
  - docker push marcusx/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-278552090824
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
